# cloudbuild.yaml
# Configuración de Cloud Build para despliegue automatizado

steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/ark-tribe-manager", "."]

  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/ark-tribe-manager"]

  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "ark-tribe-manager"
      - "--image"
      - "gcr.io/$PROJECT_ID/ark-tribe-manager"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--memory"
      - "512Mi"
      - "--port"
      - "8080"

images:
  - "gcr.io/$PROJECT_ID/ark-tribe-manager"
